package vn.linkid.sdk.models.gift

data class GiftInfo(
    val code: String?,
    val name: String?,
    val description: String?,
    val introduce: String?,
    val fullGiftCategoryCode: String?,
    val producer: String?,
    val vendor: String?,
    val effectiveFrom: String?,
    val effectiveTo: String?,
    val requiredCoin: Double?,
    val status: String?,
    val totalQuantity: Int?,
    val usedQuantity: Int?,
    val remainingQuantity: Int?,
    val fullPrice: Double?,
    val discountPrice: Double?,
    val isEGift: Boolean?,
    val tag: String?,
    val isInWishlist: Boolean?,
    val id: Int?,
    val regionCode: String?,
//    val office: String?,
    val expireDuration: String?,
    val totalWish: Int?,
    val doubleProduce: String?,  // Assuming "doubleroduce" was a typo in your Dart code
    val vendorHotline: String?,
    val isTypeCashout: Boolean?,
    val vendorName: String?,
    val vendorType: String?,
    val vendorImage: String?,
    val vendorDescription: String?,
    val merchantId: Int?,
    val merchantName: String?,
    val merchantAvatar: String?,
    val merchantDescription: String?,
    val brandId: Int?,
    val brandName: String?,
    val brandAddress: String?,
    val brandDescription: String?,
    val brandLinkLogo: String?,
    val isBrandFavourite: Boolean?,
    val commisPercentCategory: Int?,
    val thirdPartyCategoryName: String?,
    val thirdPartyGiftCode: String?,
    val giftGroups: List<GiftGroupInside>?, // Assuming existence of a GiftGroupInside data class
    val condition: String?,
    val officeAddress: String?,
    val contactEmail: String?,
    val contactHotline: String?,
    val totalRedeemedOfUser: Int?,
    val maxAllowedRedemptionOfUser: Int?,
    val maxQuantityPerRedemptionOfUser: Int?
)